### ISSUE TITLE
Missing Visual Studio project files

### ISSUE THREAD

**Issue by incompl-te** [jonpad01/My-Marvin#1]
Had a chance to look at this project again tonight and saw you made a bunch of commits, so I tried to pull them down and hit an issue.

Marvin and Injector project files are still referenced from the Solution file in the root directory, but don't exist anymore:

https://github.com/jonpad01/My-Marvin/blob/e7a5dedb56b277b68044f172f82fd0c9104c003e/Marvin.sln#L6
https://github.com/jonpad01/My-Marvin/blob/e7a5dedb56b277b68044f172f82fd0c9104c003e/Marvin.sln#L8

This makes it harder to build this project.  Can you please add the files back with your latest working version?  I tried to copy the project files from the last version in this repo, but I was still hitting linking errors when trying to build after that.

Thank you!

**Comment by jonpad01** [comment]
I added the files and was able to load the project, i changed some stuff so
im not sure if it will work in zones other than devastation at the moment.
remember to build it with x86 release mode.

**Comment by incompl-te** [comment]
I pulled your newest changes, and the project compiled right away.  Thank you!
